# Generated by Django 4.1.4 on 2022-12-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annance',
            fields=[
                ('idAnnance', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('surface', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('prix', models.IntegerField(null=True)),
                ('wilaya', models.CharField(max_length=50)),
                ('commune', models.CharField(max_length=50)),
                ('adresse', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=200)),
                ('idAnnancePreféré', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_annance.annance')),
            ],
            options={
                'order_with_respect_to': 'idAnnancePreféré',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idMessage', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField(max_length=250)),
            ],
            options={
                'order_with_respect_to': 'idMessage',
            },
        ),
        migrations.AddField(
            model_name='annance',
            name='idAnnanceur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_annance.user'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('idPhoto', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('idAnnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_annance.annance')),
            ],
            options={
                'order_with_respect_to': 'idAnnance',
            },
        ),
        migrations.AlterOrderWithRespectTo(
            name='annance',
            order_with_respect_to='idAnnanceur',
        ),
    ]
