# Generated by Django 4.1.4 on 2022-12-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_annance', '0002_alter_annance_idannanceur_alter_photo_idannance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annance',
            name='idAnnanceur',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app_annance.user'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='idAnnance',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app_annance.annance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idAnnancePreféré',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app_annance.annance'),
        ),
    ]
