# Generated by Django 4.1.4 on 2022-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_annance', '0004_alter_annance_idannanceur_alter_photo_idannance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annance',
            name='idAnnanceur',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='idAnnance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='idAnnancePreféré',
            field=models.IntegerField(),
        ),
        migrations.AlterOrderWithRespectTo(
            name='annance',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='message',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='photo',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='user',
            order_with_respect_to=None,
        ),
    ]
